# Generated by Django 4.1.3 on 2023-09-26 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_remove_talentprofile_postal_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentprofile",
            name="tbc_program_interest",
        ),
    ]
