# Generated by Django 4.1.13 on 2024-03-03 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0023_alter_job_department"),
        ("member", "0004_remove_talentprofile_talent_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TalentProfile",
            new_name="MemberProfile",
        ),
    ]
