# Generated by Django 4.1.3 on 2024-03-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_rename_talentprofile_memberprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="compensation_cash",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="compensation_equity",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="compensation_none",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="compensation_paid",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="experience_advisory",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="experience_board",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="experience_c_level",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="experience_director",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="experience_vp",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="role_c_level",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="time_commitment_annually",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="time_commitment_bi_annually",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="time_commitment_monthly",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="time_commitment_quarterly",
        ),
    ]
