# Generated by Django 4.1.3 on 2024-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0023_alter_job_department"),
        ("member", "0006_remove_memberprofile_compensation_cash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="max_compensation",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="min_compensation",
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="company_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_company_types",
                to="company.companytypes",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="industries",
            field=models.ManyToManyField(
                blank=True, related_name="member_industries", to="company.industries"
            ),
        ),
    ]
