# Generated by Django 4.1.3 on 2023-09-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_userprofile_instagram_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="timezone",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="member_spotlight",
            field=models.ManyToManyField(null=True, to="core.membersspotlight"),
        ),
    ]
