# Generated by Django 4.1.3 on 2023-10-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_remove_userprofile_timezone_and_more")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_mentor_interviewing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_mentor_profile_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_mentor_profile_removed",
            field=models.BooleanField(default=False),
        ),
    ]
