# Generated by Django 4.1.3 on 2023-12-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_customuser_is_mentor_interviewing_and_more")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="identity_ethic",
            field=models.ManyToManyField(
                blank=True, null=True, to="core.ethicidentities"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_gender",
            field=models.ManyToManyField(
                blank=True, null=True, to="core.genderidentities"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_pronouns",
            field=models.ManyToManyField(
                blank=True, null=True, to="core.pronounsidentities"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_sexuality",
            field=models.ManyToManyField(
                blank=True, null=True, to="core.sexualidentities"
            ),
        ),
    ]
