# Generated by Django 4.1.3 on 2023-12-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_alter_userprofile_identity_ethic_and_more")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_care_giver_displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_disability_displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_identity_ethic_displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_identity_gender_displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_identity_sexuality_displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_veteran_status_displayed",
            field=models.BooleanField(default=False),
        ),
    ]
