# Generated by Django 4.1.3 on 2024-01-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_userprofile_is_care_giver_displayed_and_more")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_member_onboarding_complete",
            field=models.BooleanField(default=False),
        )
    ]
