# Generated by Django 4.1.3 on 2024-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_customuser_is_member_onboarding_complete")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="identity_ethic",
            field=models.ManyToManyField(blank=True, to="core.ethicidentities"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_gender",
            field=models.ManyToManyField(blank=True, to="core.genderidentities"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_pronouns",
            field=models.ManyToManyField(blank=True, to="core.pronounsidentities"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="identity_sexuality",
            field=models.ManyToManyField(blank=True, to="core.sexualidentities"),
        ),
    ]
