# Generated by Django 4.1.3 on 2024-02-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0009_alter_userprofile_identity_ethic_and_more")]

    operations = [
        migrations.RenameField(
            model_name="ethicidentities", old_name="ethnicity", new_name="name"
        ),
        migrations.RenameField(
            model_name="genderidentities", old_name="gender", new_name="name"
        ),
        migrations.RenameField(
            model_name="pronounsidentities", old_name="pronouns", new_name="name"
        ),
        migrations.RenameField(
            model_name="sexualidentities", old_name="identity", new_name="name"
        ),
    ]
