# Generated by Django 4.1.3 on 2024-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_rename_ethnicity_ethicidentities_name_and_more")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_slack_invite_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="member_spotlight",
            field=models.ManyToManyField(blank=True, to="core.membersspotlight"),
        ),
    ]
