# Generated by Django 4.1.13 on 2024-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0011_customuser_is_slack_invite_sent_and_more")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="tbc_program_interest",
            field=models.TextField(blank=True, max_length=37, null=True),
        )
    ]
