# Generated by Django 4.1.13 on 2024-03-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_customuser_is_company_onboarding_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_review_tokens",
            field=models.IntegerField(default=3),
        ),
    ]
