# Generated by Django 4.1.13 on 2024-04-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0018_userverificationtoken")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_open_doors",
            field=models.BooleanField(default=False),
        )
    ]
