# Generated by Django 4.1.13 on 2024-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_customuser_is_open_doors")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_open_doors_onboarding_complete",
            field=models.BooleanField(default=False),
        )
    ]
