# Generated by Django 4.2.11 on 2024-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0022_made_community_needs_db")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="tbc_program_interest"),
        migrations.AddField(
            model_name="userprofile",
            name="program_interest",
            field=models.ManyToManyField(to="core.communityneeds"),
        ),
    ]
