# Generated by Django 4.2.11 on 2024-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0023_remove_userprofile_tbc_program_interest_and_more")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="program_interest"),
        migrations.AddField(
            model_name="userprofile",
            name="tbc_program_interest",
            field=models.ManyToManyField(to="core.communityneeds"),
        ),
    ]
