# Generated by Django 4.2.11 on 2024-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0024_remove_userprofile_program_interest_and_more")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_migrated_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.FileField(
                blank=True, max_length=400, null=True, upload_to="users"
            ),
        ),
    ]
