# Generated by Django 4.2.13 on 2024-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_is_migrated_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityneeds',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ethicidentities',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='genderidentities',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pronounsidentities',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sexualidentities',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
