# Generated by Django 4.2.13 on 2024-07-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_communityneeds_normalized_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_open_doors_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
