# Generated by Django 4.2.13 on 2024-07-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customuser_is_open_doors_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sendgrid_invite_sent',
            field=models.BooleanField(default=False),
        ),
    ]
