# Generated by Django 4.2.13 on 2024-08-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_soft_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
