# Generated by Django 4.2.13 on 2024-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_added_tracking_for_slack_id_for_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_slack_active',
            field=models.BooleanField(default=False),
        ),
    ]
