# Generated by Django 4.2.13 on 2024-08-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tracking_for_slack_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_slack_found_with_user_email',
            field=models.BooleanField(default=False),
        ),
    ]
