# Generated by Django 4.1.3 on 2024-01-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0017_mentorroster_sessions_session")]

    operations = [
        migrations.AlterField(
            model_name="mentorroster",
            name="mentee_review_of_mentor",
            field=models.ManyToManyField(
                blank=True, related_name="mentee_reviews", to="mentorship.mentorreview"
            ),
        ),
        migrations.AlterField(
            model_name="mentorroster",
            name="mentor_review_of_mentee",
            field=models.ManyToManyField(
                blank=True, related_name="mentor_reviews", to="mentorship.mentorreview"
            ),
        ),
    ]
