# Generated by Django 4.1.3 on 2024-01-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0018_alter_mentorroster_mentee_review_of_mentor_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorroster",
            name="sessions",
            field=models.ManyToManyField(
                related_name="mentor_roster_sessions", to="mentorship.session"
            ),
        )
    ]
