# Generated by Django 4.1.3 on 2024-01-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0019_alter_mentorroster_sessions")]

    operations = [
        migrations.RemoveField(model_name="mentorprofile", name="commitment_level"),
        migrations.AddField(
            model_name="menteeprofile",
            name="commitment_level",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="mentor_commitment_level",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="mentor_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentor_support_areas",
                to="mentorship.mentorsupportareas",
            ),
        ),
    ]
