# Generated by Django 4.1.3 on 2024-01-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0019_alter_mentorroster_sessions")]

    operations = [
        migrations.AddField(
            model_name="menteeprofile",
            name="commitment_level",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="commitment_level",
            field=models.ManyToManyField(
                blank=True,
                related_name="commitment_level",
                to="mentorship.mentorsupportareas",
            ),
        ),
    ]
