# Generated by Django 4.1.3 on 2024-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0020_menteeprofile_commitment_level_and_more")]

    operations = [
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="mentor_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="commitment_level",
                to="mentorship.mentorsupportareas",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="commitment_level",
            field=models.ManyToManyField(
                related_name="commitment_level", to="mentorship.commitmentlevel"
            ),
        ),
    ]
