# Generated by Django 4.1.3 on 2024-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mentorship",
            "0022_rename_commitment_level_menteeprofile_mentee_commitment_level_and_more",
        )
    ]

    operations = [
        migrations.RenameField(
            model_name="menteeprofile",
            old_name="mentee_commitment_level",
            new_name="commitment_level",
        ),
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="mentor_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentor_support_areas",
                to="mentorship.mentorsupportareas",
            ),
        ),
    ]
