# Generated by Django 4.1.3 on 2023-10-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="lever_xml_feed_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=140)),
                ("description", django_quill.fields.QuillField()),
                ("url", models.CharField(max_length=300)),
                (
                    "interview_process",
                    django_quill.fields.QuillField(blank=True, null=True),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full time", "full time"),
                            ("part time", "part time"),
                            ("contract", "contracting"),
                            ("volunteer", "volunteer"),
                            ("temporary", "temporary"),
                            ("internship", "internship"),
                            ("apprenticeship", "apprenticeship"),
                        ],
                        default="full time",
                        max_length=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=7,
                    ),
                ),
                (
                    "on_site_remote",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                        ],
                        default=(
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                        ),
                        max_length=7,
                    ),
                ),
                ("compensation_paid", models.BooleanField(default=False)),
                ("compensation_equity", models.BooleanField(default=False)),
                ("compensation_none", models.BooleanField(default=False)),
                (
                    "compensation_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "experience",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "years_of_experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "0 years"),
                            ("2", "1 - 2 years"),
                            ("3", "3 - 5 years"),
                            ("4", "6 - 10 years"),
                            ("5", "11 - 15  years"),
                            ("6", "16 - 20 years"),
                            ("7", "21+ years"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now=True, verbose_name="date published"),
                ),
                ("sourced_talent_from_us", models.BooleanField(default=False)),
                ("featured_job", models.BooleanField(default=False)),
                ("is_referral_job", models.BooleanField(default=False)),
                ("team_size", models.IntegerField(blank=True, null=True)),
                ("female_team_size_total", models.IntegerField(blank=True, null=True)),
                ("poc_team_size_total", models.IntegerField(blank=True, null=True)),
                ("black_team_size_total", models.IntegerField(blank=True, null=True)),
                (
                    "indigenous_team_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("lgbtqia_team_size_total", models.IntegerField(blank=True, null=True)),
                (
                    "disabled_team_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("department_size", models.IntegerField(blank=True, null=True)),
                (
                    "female_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "poc_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "black_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "indigenous_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "lgbtqia_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "disabled_department_size_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_paid", models.BooleanField(default=False, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lever_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("department", models.ManyToManyField(to="company.department")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.joblevel",
                    ),
                ),
                (
                    "max_compensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="max_salary_band",
                        to="company.salaryrange",
                    ),
                ),
                (
                    "min_compensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="min_salary_band",
                        to="company.salaryrange",
                    ),
                ),
                (
                    "parent_company",
                    models.ForeignKey(
                        default=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_role_types",
                        to="company.roles",
                    ),
                ),
                ("skills", models.ManyToManyField(to="company.skill")),
            ],
        ),
    ]
