# Generated by Django 4.1.3 on 2023-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0002_companyprofile_lever_xml_feed_url_job")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="industries",
            field=models.ManyToManyField(
                blank=True, null=True, to="company.industries"
            ),
        )
    ]
