# Generated by Django 4.1.3 on 2023-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0003_alter_companyprofile_industries")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("1 - 20", "1 - 20"),
                    ("21 - 100", "21 - 100"),
                    ("101 - 500", "101 - 500"),
                    ("501 - 1000", "501 - 1000"),
                    ("1001 - 5000", "1001 - 5000"),
                    ("5001", "5001"),
                ],
                max_length=11,
            ),
        )
    ]
