# Generated by Django 4.1.3 on 2023-10-28 16:44

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [("company", "0004_alter_companyprofile_company_size")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="mission",
            field=django_quill.fields.QuillField(blank=True, null=True),
        )
    ]
