# Generated by Django 4.1.3 on 2023-10-29 16:17

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [("company", "0005_alter_companyprofile_mission")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="external_description",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
