# Generated by Django 4.1.3 on 2023-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0006_job_external_description_alter_job_description")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="on_site_remote",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                    ("unknown", "unknown"),
                ],
                default=(
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                    ("unknown", "unknown"),
                ),
                max_length=7,
            ),
        )
    ]
