# Generated by Django 4.1.3 on 2023-10-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("company", "0007_alter_job_on_site_remote")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.joblevel",
            ),
        )
    ]
