# Generated by Django 4.1.3 on 2023-10-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("company", "0008_alter_job_level")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="max_compensation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="max_salary_band",
                to="company.salaryrange",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_compensation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="min_salary_band",
                to="company.salaryrange",
            ),
        ),
    ]
