# Generated by Django 4.1.3 on 2023-11-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0009_alter_job_max_compensation_and_more")]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="greenhouse_api_key",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="lever_api_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
