# Generated by Django 4.1.3 on 2023-11-10 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0011_alter_companyprofile_company_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialHiringNeeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_location", models.CharField(max_length=280)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("HOLD", "On Hold"),
                            ("REVIEWING", "Reviewing"),
                            ("COMPANY_DETAILS_NEEDED", "Company Details Needed"),
                            ("JOB_DETAILS_NEEDED", "Job Details Needed"),
                            ("REJECTED_BAD_COMPANY", "Rejected Bad Company"),
                            ("REJECTED_ROLE_ALIGNMENT", "Rejected Role Alignment"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="SENT",
                        max_length=23,
                    ),
                ),
                (
                    "job_site",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                            ("unknown", "unknown"),
                        ],
                        default=(
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                            ("unknown", "unknown"),
                        ),
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                    ),
                ),
                ("job_roles", models.ManyToManyField(to="company.roles")),
            ],
        )
    ]
