# Generated by Django 4.1.3 on 2023-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0012_initialhiringneeds")]

    operations = [
        migrations.AlterField(
            model_name="initialhiringneeds",
            name="job_site",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                    ("unknown", "unknown"),
                ],
                default=(
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                    ("unknown", "unknown"),
                ),
                max_length=250,
            ),
        )
    ]
