# Generated by Django 4.1.3 on 2023-11-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0013_alter_initialhiringneeds_job_site")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="external_interview_process",
            field=models.CharField(blank=True, max_length=3000, null=True),
        )
    ]
