# Generated by Django 4.1.3 on 2023-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0014_job_external_interview_process")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pause", "Pause"),
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                    ("job_expired", "Job Expired"),
                    ("company_details_needed", "Company Details Needed"),
                    ("job_details_needed", "Job Details Needed"),
                    ("rejected_bad_company", "Rejected Bad Company"),
                    ("rejected_role_alignment", "Rejected Role Alignment"),
                ],
                default="draft",
                max_length=23,
            ),
        )
    ]
