# Generated by Django 4.1.3 on 2023-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0015_alter_job_status")]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        )
    ]
