# Generated by Django 4.1.3 on 2023-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0016_companyprofile_logo_url")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_pull_remoteio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type_str",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
