# Generated by Django 4.1.3 on 2023-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0017_job_is_pull_remoteio_job_job_type_str")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full time", "full time"),
                    ("part time", "part time"),
                    ("contract", "contracting"),
                    ("contract", "contracting"),
                    ("volunteer", "volunteer"),
                    ("temporary", "temporary"),
                    ("internship", "internship"),
                    ("apprenticeship", "apprenticeship"),
                ],
                default="full time",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="on_site_remote",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
    ]
