# Generated by Django 4.1.3 on 2023-12-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("company", "0018_alter_job_job_type_alter_job_on_site_remote")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.ManyToManyField(
                blank=True, null=True, to="company.department"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_role_types",
                to="company.roles",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(blank=True, null=True, to="company.skill"),
        ),
    ]
