# Generated by Django 4.1.3 on 2023-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0019_alter_job_department_alter_job_role_alter_job_skills")
    ]

    operations = [
        migrations.RemoveField(model_name="interviewrequest", name="candidate"),
        migrations.RemoveField(model_name="interviewrequest", name="company"),
        migrations.AddField(
            model_name="job",
            name="referral_note",
            field=models.TextField(default=False, max_length=1000),
        ),
        migrations.DeleteModel(name="InitialHiringNeeds"),
        migrations.DeleteModel(name="InterviewRequest"),
    ]
