# Generated by Django 4.1.3 on 2024-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0021_alter_job_referral_note")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="industries",
            field=models.ManyToManyField(blank=True, to="company.industries"),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(blank=True, to="company.skill"),
        ),
    ]
