# Generated by Django 4.1.3 on 2024-03-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0023_alter_job_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="talent_choice_account",
            field=models.BooleanField(default=False),
        ),
    ]
