# Generated by Django 4.1.13 on 2024-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0025_remove_companyprofile_account_subscription_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_benefits",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_diversity_statement",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_highlights",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="ethics_statement",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="mission",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="tag_line",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="vision",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
