# Generated by Django 4.2.11 on 2024-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0027_companyprofile_coresignal_id")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="mission",
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="vision",
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
    ]
