# Generated by Django 4.2.11 on 2024-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0028_extended_max_char_length")]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_url",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="logo_url",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
