# Generated by Django 4.2.11 on 2024-06-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0029_extended_max_char_length_mutiple_fields")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="external_id",
            field=models.CharField(blank=True, max_length=140, null=True),
        )
    ]
