# Generated by Django 4.2.11 on 2024-06-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0030_add_external_id")]

    operations = [
        migrations.AlterField(
            model_name="industries",
            name="webflow_item_id",
            field=models.CharField(blank=True, max_length=400, null=True),
        )
    ]
