# Generated by Django 4.2.11 on 2024-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0031_alter_industries_webflow_item_id")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="external_description",
            field=models.CharField(blank=True, max_length=6000, null=True),
        )
    ]
