# Generated by Django 4.2.11 on 2024-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0033_alter_job_created_by")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="external_description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        )
    ]
