# Generated by Django 4.2.11 on 2024-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0034_alter_job_external_description")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="external_description",
            field=models.CharField(blank=True, max_length=20000, null=True),
        )
    ]
