# Generated by Django 4.2.11 on 2024-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0036_certs_job_nice_to_have_skills_job_certs")]

    operations = [
        migrations.RemoveField(model_name="certs", name="webflow_item_id"),
        migrations.AddField(
            model_name="certs",
            name="details",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="certs",
            name="roles",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
