# Generated by Django 4.2.13 on 2024-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_remove_job_created_by_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='certs',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companytypes',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='industries',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
