# Generated by Django 4.1.3 on 2024-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("talent", "0003_remove_talentprofile_tbc_program_interest")]

    operations = [
        migrations.RemoveField(model_name="talentprofile", name="talent_status"),
        migrations.AddField(
            model_name="talentprofile",
            name="is_talent_status",
            field=models.BooleanField(default=False),
        ),
    ]
