# Generated by Django 4.1.3 on 2023-10-03 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('quill', 'Quill'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=20)),
                ('question_group', models.CharField(choices=[('career', 'Career'), ('mentorship', 'Mentorship')], max_length=10)),
                ('helper_text', models.TextField()),
                ('application_type', models.CharField(choices=[('mentor_only', 'Mentor Only'), ('mentee_only', 'Mentee Only'), ('both', 'Both')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=116)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at_date', models.DateTimeField(blank=True, null=True)),
                ('interview_requested_at_date', models.DateTimeField(blank=True, null=True)),
                ('paused_date', models.DateTimeField(blank=True, null=True)),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('removed_coc_date', models.DateTimeField(blank=True, null=True)),
                ('removed_inactive_date', models.DateTimeField(blank=True, null=True)),
                ('interview_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at_date', models.DateTimeField(blank=True, null=True)),
                ('interview_requested_at_date', models.DateTimeField(blank=True, null=True)),
                ('paused_date', models.DateTimeField(blank=True, null=True)),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('removed_coc_date', models.DateTimeField(blank=True, null=True)),
                ('removed_inactive_date', models.DateTimeField(blank=True, null=True)),
                ('interview_reminder_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_review_of_mentor', django_quill.fields.QuillField(blank=True, null=True)),
                ('mentor_review_of_mentee', django_quill.fields.QuillField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSupportAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=116)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_power', models.IntegerField(blank=True, null=True)),
                ('value_achievement', models.IntegerField(blank=True, null=True)),
                ('value_hedonism', models.IntegerField(blank=True, null=True)),
                ('value_stimulation', models.IntegerField(blank=True, null=True)),
                ('value_self_direction', models.IntegerField(blank=True, null=True)),
                ('value_universalism', models.IntegerField(blank=True, null=True)),
                ('value_benevolence', models.IntegerField(blank=True, null=True)),
                ('value_tradition', models.IntegerField(blank=True, null=True)),
                ('value_conformity', models.IntegerField(blank=True, null=True)),
                ('value_security', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipProgramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_link', models.URLField(blank=True, null=True)),
                ('tbc_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mentee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.menteeprofile')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorprofile')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorroster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.valuesmatch')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.applicationquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
