# Generated by Django 4.2.11 on 2024-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="menteeprofile",
            name="commitment_level",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="mentor_commitment_level",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
    ]
