# Generated by Django 4.1.3 on 2023-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationquestion",
            name="helper_text",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
