# Generated by Django 4.2.13 on 2024-07-28 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentorprofile_created_at_mentorprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
