# Generated by Django 4.1.3 on 2023-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0002_alter_applicationquestion_helper_text")]

    operations = [
        migrations.AddField(
            model_name="menteeprofile",
            name="mentee_support_areas",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="commitment_level",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="biggest_strengths",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="career_goals",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="career_milestones",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="career_success",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="commitment_level",
            field=models.ManyToManyField(
                related_name="commitment_level", to="mentorship.commitmentlevel"
            ),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_achievement",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_benevolence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_conformity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_hedonism",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_power",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_security",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_self_direction",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_stimulation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_tradition",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="value_universalism",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="work_motivation",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
