# Generated by Django 4.1.3 on 2023-11-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0003_menteeprofile_mentee_support_areas_and_more")]

    operations = [
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="mentee_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mentorship.menteeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="mentor_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mentorship.mentorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="values",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mentorship.valuesmatch",
            ),
        ),
    ]
