# Generated by Django 4.2.13 on 2024-07-28 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_menteeprofile_created_at_menteeprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
