# Generated by Django 4.1.3 on 2023-11-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0004_alter_mentorshipprogramprofile_mentee_profile_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorshipprogramprofile",
            name="roster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mentorship.mentorroster",
            ),
        )
    ]
