# Generated by Django 4.1.3 on 2023-11-25 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mentorship", "0005_alter_mentorshipprogramprofile_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="user",
            field=models.ForeignKey(
                default=90,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        )
    ]
