# Generated by Django 4.2.11 on 2024-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0005_alter_mentorshipprogramprofile_user")]

    operations = [
        migrations.AddField(
            model_name="menteeprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(
                blank=True, to="mentorship.mentorsupportareas"
            ),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentee_support_areas",
                to="mentorship.mentorsupportareas",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="mentor_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentor_support_areas",
                to="mentorship.mentorsupportareas",
            ),
        ),
    ]
