# Generated by Django 4.1.3 on 2023-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0006_mentorprofile_user")]

    operations = [
        migrations.RemoveField(model_name="menteeprofile", name="mentee_support_areas"),
        migrations.AddField(
            model_name="menteeprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(
                blank=True, null=True, to="mentorship.commitmentlevel"
            ),
        ),
    ]
