# Generated by Django 4.1.3 on 2023-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0007_remove_menteeprofile_mentee_support_areas_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="menteeprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        )
    ]
