# Generated by Django 4.1.3 on 2023-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0008_alter_menteeprofile_mentee_support_areas")]

    operations = [
        migrations.RemoveField(model_name="mentorprofile", name="mentor_support_areas"),
        migrations.AddField(
            model_name="mentorprofile",
            name="mentor_support_areas",
            field=models.ManyToManyField(blank=True, to="mentorship.commitmentlevel"),
        ),
    ]
