# Generated by Django 4.1.3 on 2023-12-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0011_remove_menteeprofile_mentor_how_to_help_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorroster", name="mentee_review_of_mentor"
        ),
        migrations.RemoveField(
            model_name="mentorroster", name="mentor_review_of_mentee"
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "review_author",
                    models.CharField(
                        choices=[("mentor", "Mentor"), ("mentee", "Mentee")],
                        max_length=6,
                    ),
                ),
                (
                    "review_content",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.menteeprofile",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mentorroster",
            name="mentee_review_of_mentor",
            field=models.ManyToManyField(
                related_name="mentee_reviews", to="mentorship.mentorreview"
            ),
        ),
        migrations.AddField(
            model_name="mentorroster",
            name="mentor_review_of_mentee",
            field=models.ManyToManyField(
                related_name="mentor_reviews", to="mentorship.mentorreview"
            ),
        ),
    ]
