# Generated by Django 4.1.3 on 2023-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0012_remove_mentorroster_mentee_review_of_mentor_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="menteeprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(
                blank=True, to="mentorship.mentorsupportareas"
            ),
        )
    ]
