# Generated by Django 4.1.3 on 2023-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0013_alter_menteeprofile_mentee_support_areas")]

    operations = [
        migrations.AddField(
            model_name="mentorshipprogramprofile",
            name="mentee_support_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentee_support_areas",
                to="mentorship.mentorsupportareas",
            ),
        )
    ]
