# Generated by Django 4.1.3 on 2023-12-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0014_mentorshipprogramprofile_mentee_support_areas")
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="mentor_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("active", "Active"),
                    ("interviewing", "Interviewing"),
                    ("paused", "Paused"),
                    ("removed", "Removed"),
                    ("removed_coc_issues", "Removed COC Issues"),
                    ("removed_inactive", "Removed Inactive"),
                    ("incomplete_application", "Incomplete Application"),
                    ("lacking_experience", "Lacking Skill or Experience"),
                    ("rejected_other", "Other"),
                    ("passed_interview", "Passed Interview"),
                ],
                default=1,
                max_length=22,
            ),
        )
    ]
