# Generated by Django 4.1.3 on 2024-01-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0015_mentorprofile_mentor_status")]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="mentor_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("active", "Active"),
                    ("interviewing", "Interviewing"),
                    ("paused", "Paused"),
                    ("need_cal_info", "Need Booking Info"),
                    ("removed", "Removed"),
                    ("removed_coc_issues", "Removed COC Issues"),
                    ("removed_inactive", "Removed Inactive"),
                    ("incomplete_application", "Incomplete Application"),
                    ("lacking_experience", "Lacking Skill or Experience"),
                    ("rejected_other", "Other"),
                    ("passed_interview", "Passed Interview"),
                ],
                default=1,
                max_length=22,
            ),
        )
    ]
