# Generated by Django 4.1.3 on 2024-01-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mentorship",
            "0017_rename_commitment_level_mentorprofile_mentor_commitment_level_and_more",
        )
    ]

    operations = [
        migrations.RenameField(
            model_name="mentorprofile",
            old_name="commitment_level",
            new_name="mentor_commitment_level",
        )
    ]
