# Generated by Django 4.1.3 on 2024-01-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0015_mentorprofile_mentor_commitment_level_and_more"),
        (
            "mentorship",
            "0018_rename_commitment_level_mentorprofile_mentor_commitment_level",
        ),
    ]

    operations = []
