# Generated by Django 4.1.3 on 2024-01-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mentorship", "0019_merge_20240116_0103")]

    operations = [
        migrations.RemoveField(model_name="mentorprofile", name="mentor_support_areas")
    ]
